"""Layered configuration: defaults -> data/config.toml -> environment.

See plan/10-spine.md §6. Keep this small; attachment-specific config is sliced
out per attachment via ``Settings.attachment_config``.
"""

from __future__ import annotations

import os
import sys
import tomllib
from functools import lru_cache
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field
from pydantic_settings import BaseSettings, SettingsConfigDict


def _frozen_root() -> Path | None:
    """The PyInstaller bundle root (``sys._MEIPASS``) when running as a frozen
    one-file/-dir binary, else None. Datafiles added in the .spec land here."""
    if getattr(sys, "frozen", False):
        return Path(getattr(sys, "_MEIPASS", Path(sys.executable).resolve().parent))
    return None


def _default_data_dir() -> Path:
    """Where SQLite, secrets and attachment data live by default.

    - Source checkout: backend/data/ (gitignored), as before.
    - Frozen binary: a per-user OS location, because the binary itself may sit
      somewhere read-only (e.g. /usr/local/bin, Program Files). The installer
      can still override via RASPY_DATA_DIR, but this default means a
      double-clicked binary works with no config at all.
    """
    if _frozen_root() is not None:
        if sys.platform == "win32":
            base = Path(os.environ.get("APPDATA", Path.home() / "AppData" / "Roaming"))
        elif sys.platform == "darwin":
            base = Path.home() / "Library" / "Application Support"
        else:
            base = Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local" / "share"))
        return base / "raspy"
    return Path(__file__).resolve().parent.parent / "data"


def _default_static_dir() -> Path:
    """The built SvelteKit bundle the spine serves.

    - Source checkout: repo's frontend/build/ (backend/raspy/ -> ../../frontend/build).
    - Frozen binary: the bundle is packed into sys._MEIPASS/frontend by the .spec.
    """
    root = _frozen_root()
    if root is not None:
        return root / "frontend"
    return Path(__file__).resolve().parent.parent.parent / "frontend" / "build"


# Repo-relative (or per-user, when frozen) default data dir.
_DEFAULT_DATA_DIR = _default_data_dir()

# Default static bundle: the SvelteKit build output the spine serves in production.
_DEFAULT_STATIC_DIR = _default_static_dir()


class AuthSettings(BaseModel):
    """Auth tuning — see plan/30-auth-security.md. All overridable via
    config.toml's ``[auth]`` table or ``RASPY_AUTH__<field>`` env vars.

    Argon2 params are deliberately conservative defaults; run
    ``raspy-auth calibrate`` on the actual Pi and write the result here so a
    verify lands at ~250–500ms. They are stored *per account* at creation too,
    so changing these here only affects newly created/re-hashed credentials.
    """

    # Token lifetimes.
    access_ttl_s: int = 15 * 60          # short — a stolen access token is brief
    refresh_ttl_s: int = 7 * 24 * 60 * 60  # 7 days, rotating

    # Argon2id parameters (used for password + PIN hashing).
    argon_time_cost: int = 3
    argon_memory_kib: int = 64 * 1024    # 64 MiB
    argon_parallelism: int = 2

    # Rate limit / lockout (per account and per IP).
    max_attempts: int = 5                # consecutive failures before lockout
    lockout_base_s: float = 2.0          # exponential: base * 2**(fails-max)
    lockout_cap_s: float = 15 * 60.0
    # After this many failed PIN unlocks, downgrade the family so the next
    # prompt is the full password (forces a real re-login).
    pin_max_attempts: int = 3

    # Cookies. Secure must be true in production (HTTPS end-to-end as the client
    # sees it). Allow disabling for plain-http LAN dev.
    cookie_secure: bool = True
    cookie_samesite: str = "lax"
    csrf_enabled: bool = True

    # Only honor X-Forwarded-For from these immediate peers (the local reverse
    # layer: cloudflared / Caddy on the box). Otherwise rate-limit-by-IP could
    # be spoofed. Empty => never trust the header, use the socket peer.
    trusted_proxies: list[str] = Field(default_factory=lambda: ["127.0.0.1", "::1"])


class ChannelSettings(BaseModel):
    """Layer-1 encrypted-channel settings (see plan). The static keypair is
    generated by ``raspy-auth`` into ``data/channel_key``; here we only tune
    behaviour."""

    enabled: bool = True
    # How long an established channel session is valid before a re-handshake.
    session_ttl_s: int = 24 * 60 * 60


class Settings(BaseSettings):
    """Runtime settings for the spine."""

    model_config = SettingsConfigDict(
        env_prefix="RASPY_",
        env_nested_delimiter="__",
        extra="ignore",
    )

    host: str = "127.0.0.1"
    port: int = 49317

    # Auth + channel sub-configs (config.toml [auth] / [channel] tables).
    auth: AuthSettings = Field(default_factory=AuthSettings)
    channel: ChannelSettings = Field(default_factory=ChannelSettings)

    # CORS allow-list. The served shell is same-origin; add the Vite dev origin
    # and any Capacitor/Flutter origin here. Credentialed (cookie) CORS forbids
    # "*", so this must be an explicit list in production.
    cors_origins: list[str] = Field(
        default_factory=lambda: [
            "http://localhost:5173",
            "http://127.0.0.1:5173",
        ]
    )

    # Where SQLite, secrets and per-attachment data live.
    data_dir: Path = _DEFAULT_DATA_DIR

    # The built SvelteKit bundle the spine serves at the root path (everything
    # not under /api/). Defaults to the repo's frontend/build/, served in place;
    # override with RASPY_STATIC_DIR. If the dir is absent (e.g. frontend not
    # built yet), the spine still runs and the API works — only the UI is 404.
    static_dir: Path = _DEFAULT_STATIC_DIR

    # Attachments explicitly disabled by id (everything discovered is enabled
    # by default). Lets you turn one off without removing the package.
    disabled_attachments: list[str] = Field(default_factory=list)

    # Optional extra directory of drop-in attachment packages.
    # (Built-in attachments under raspy/attachments/ are always discovered.)
    attachments_dir: Path | None = None

    # Web Push (VAPID) keys for background notifications. Generate a pair with
    # `raspy-vapid` (see scripts) and set these via config.toml or env
    # (RASPY_VAPID_PUBLIC_KEY / RASPY_VAPID_PRIVATE_KEY). Without them the
    # foreground (WebSocket) notification path still works; only background push
    # to closed tabs is skipped. `vapid_subject` is the contact mailto/URL the
    # push service sees.
    vapid_public_key: str | None = None
    vapid_private_key: str | None = None
    vapid_subject: str = "mailto:admin@localhost"

    # Self-update (see plan/55-distribution.md). The spine periodically compares
    # its own __version__ against the latest GitHub Release of this repo and, on
    # one-click confirmation, downloads + swaps the matching platform binary and
    # asks the OS service manager to restart. Only meaningful for the frozen
    # binary build; a source checkout reports "not updatable".
    update_repo: str = "vardhin/raspy"          # GitHub <owner>/<repo>
    update_check_interval_s: int = 6 * 60 * 60  # 6h; 0 disables periodic checks
    # How the running service is restarted after a swap. "auto" detects the
    # platform's manager (systemd / launchd / Windows Service); "exec" re-execs
    # the process in place (used when not run under a service manager).
    update_restart_strategy: str = "auto"
    # systemd/launchd/Windows service unit name the installer registered, used to
    # trigger the restart. Empty => fall back to in-place re-exec.
    update_service_name: str = "raspy"

    # Per-attachment config blob loaded from config.toml's [attachments.<id>].
    _attachment_config: dict[str, dict[str, Any]] = {}

    @property
    def db_path(self) -> Path:
        return self.data_dir / "raspy.sqlite3"

    @property
    def auth_secret_path(self) -> Path:
        """HMAC signing secret for session tokens. Created on first account
        setup with 600 perms; never leaves the box."""
        return self.data_dir / "auth_secret"

    @property
    def channel_key_path(self) -> Path:
        """The Pi's long-term static X25519 key (PEM), for the Layer-1
        handshake. Created by ``raspy-auth`` with 600 perms."""
        return self.data_dir / "channel_key"

    def attachment_data_dir(self, attachment_id: str) -> Path:
        return self.data_dir / "att" / attachment_id

    def attachment_config(self, attachment_id: str) -> dict[str, Any]:
        return self._attachment_config.get(attachment_id, {})


def _load_toml(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    with path.open("rb") as fh:
        return tomllib.load(fh)


@lru_cache
def get_settings() -> Settings:
    """Build settings: TOML file (if present) overlaid by env vars.

    config.toml lives in the data dir. Its ``[attachments.<id>]`` tables become
    each attachment's config slice.
    """
    # We need the data dir before we can find config.toml, and the data dir may
    # itself be set via env. Resolve env-or-default first.
    bootstrap = Settings()
    toml_path = bootstrap.data_dir / "config.toml"
    raw = _load_toml(toml_path)

    attachment_cfg = raw.pop("attachments", {}) or {}
    # Remaining top-level keys override defaults but are still overridden by env
    # (BaseSettings env sources take precedence over constructor kwargs only if
    # we pass them as init — so env wins by re-reading after).
    settings = Settings(**raw)
    settings._attachment_config = attachment_cfg
    return settings
