"""Generate a VAPID keypair for Web Push.

Run ``raspy-vapid`` once and paste the output into ``data/config.toml`` (or set
the env vars). The public key is handed to the browser as the
``applicationServerKey``; the spine keeps the private key. See
core/notifications.py.

VAPID keys are an ECDSA P-256 keypair:
  - public  → base64url of the uncompressed EC point (65 bytes).
  - private → base64url of the 32-byte private scalar. pywebpush accepts this
    string directly as ``vapid_private_key``.
"""

from __future__ import annotations

import argparse
import base64
import sys

from cryptography.hazmat.primitives import serialization
from py_vapid import Vapid01


def _b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()


def generate_keypair() -> tuple[str, str]:
    """Return (public_key_b64url, private_key_b64url)."""
    vapid = Vapid01()
    vapid.generate_keys()
    public_raw = vapid.public_key.public_bytes(
        serialization.Encoding.X962,
        serialization.PublicFormat.UncompressedPoint,
    )
    private_raw = vapid.private_key.private_numbers().private_value.to_bytes(32, "big")
    return _b64url(public_raw), _b64url(private_raw)


def _toml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_into_config(subject: str = "mailto:admin@localhost") -> bool:
    """Generate a keypair and write the three vapid_* keys into the data dir's
    config.toml, unless keys are already present. Returns True if it wrote new
    keys, False if it left an existing pair alone. Used by the installer so push
    works out of the box with no manual key paste.

    Imported lazily to avoid a config import at module load.
    """
    from .config import get_settings

    settings = get_settings()
    if settings.vapid_public_key and settings.vapid_private_key:
        return False  # already configured — don't clobber

    public, private = generate_keypair()
    settings.data_dir.mkdir(parents=True, exist_ok=True)
    cfg = settings.data_dir / "config.toml"
    block = (
        "\n# Web Push (VAPID) keys — generated by the installer.\n"
        f'vapid_public_key = "{_toml_escape(public)}"\n'
        f'vapid_private_key = "{_toml_escape(private)}"\n'
        f'vapid_subject = "{_toml_escape(subject)}"\n'
    )
    with cfg.open("a", encoding="utf-8") as fh:
        fh.write(block)
    return True


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="raspy-vapid", description="Generate a VAPID keypair for Web Push"
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="write the keys straight into data/config.toml (skips if present) "
        "instead of printing them — used by the installer",
    )
    parser.add_argument(
        "--subject",
        default="mailto:admin@localhost",
        help="contact mailto:/URL the push service sees",
    )
    args = parser.parse_args()

    if args.write:
        wrote = write_into_config(args.subject)
        if wrote:
            print("VAPID keypair written to data/config.toml.")
        else:
            print("VAPID keys already present; left unchanged.")
        return

    public, private = generate_keypair()
    print("VAPID keypair generated. Add to data/config.toml:\n")
    print(f"vapid_public_key = {public!r}")
    print(f"vapid_private_key = {private!r}")
    print('vapid_subject = "mailto:you@example.com"')
    print("\n…or export as env vars:\n")
    print(f"export RASPY_VAPID_PUBLIC_KEY={public}")
    print(f"export RASPY_VAPID_PRIVATE_KEY={private}")
    sys.exit(0)


if __name__ == "__main__":
    main()
